//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lib.rc
//
#define IDS_LIB_NAME                    101
#define IDS_PROPPAGE                    102
#define IDS_CONFIRM_CLEANALL            103
#define IDS_CONFIRM_REMOVEALL           104
#define IDS_MENULABEL_REMOVECOMMENT     105
#define IDS_MENULABEL_REMOVEDRAWING     106
#define IDS_GSHAPE_COLORS               107
#define IDS_COLOR_SAMPLE_TEXT           108
#define IDS_SAVEAS_FILTER               110
#define IDS_SAVEAS_FAIL                 120
#define IDS_DATARANGEDLG_CAPTION_COPY   121
#define IDS_DATARANGEDLG_CAPTION_SAVE   122
#define IDS_DATARANGEDLG_CAPTION_PRINT  123
#define IDS_MSG_SEARCHFAIL_FILEMODIFIED 130
#define IDS_MSG_SEARCHFAIL_NOMATCH      131
#define IDS_CAPTION_FINDDATA            132
#define IDS_MSGFMT_SEARCHFAIL           133
#define IDS_MSGFMT_ERRORCODE            134
#define IDS_ASK_CANCEL_PRINT            135
#define IDS_SM_BOM_START_FAIL           150
#define IDS_SM_BOM_COMPLETED            151
#define IDS_SM_BOM_SCAN_FAIL            152
#define IDS_SM_BOM_CRLF_DETECTED        153
#define IDS_SCANNED_TAGS             154
#define IDB_JPEG_LOGO                   180
#define IDB_PNG_LOGO                    181
#define IDR_ACCEL                       200
#define IDR_VIEWPOPUP                   201
#define IDI_PROPPAGE                    240
#define IDD_PROPPAGE                    301
#define IDD_PROPPAGE_MEDIUM             302
#define IDD_PROPPAGE_LARGE              303
#define IDD_PROPPAGE2                   304
#define IDD_PROPPAGE_MEDIUM2            305
#define IDD_PROPPAGE_LARGE2             306
#define IDD_FINDDATA                    310
#define IDD_DUMPRANGE                   311
#define IDD_LOCATION                    312
#define IDD_ADD_TAG                     313
#define IDD_PRINTDLGORD2                320
#define IDD_PRINTDLGORDTEST             321
#define IDM_VKEY_LEFT                   420
#define IDM_VKEY_RIGHT                  421
#define IDM_VKEY_PRIOR                  422
#define IDM_VKEY_NEXT                   423
#define IDM_VKEY_UP                     424
#define IDM_VKEY_DOWN                   425
#define IDM_VKEY_HOME                   426
#define IDM_VKEY_END                    427
#define IDM_BPL_8                       450
#define IDM_BPL_16                      451
#define IDM_BPL_32                      452
#define IDM_SAME_FONTSIZE               455
#define IDM_OPEN_NEW_WINDOW             456
#define IDM_SAVEMETA                    457
#define IDM_FINDPREV                    460
#define IDM_FINDNEXT                    461
#define IDM_FINDDATA                    462
#define IDM_FINDPREV_METAITEM           465
#define IDM_FINDNEXT_METAITEM           466
#define IDM_COPYDATA                    470
#define IDM_SAVEDATA                    471
#define IDM_PRINTDATA                   472
#define IDM_PRINT_EVENT_NOTIF           473
#define IDM_UPDATE_PAGENUM              475
#define IDM_SCANTAG_START               480
#define IDM_SCANTAG_FINISH              481
#define IDM_LIST_SCANNED_TAGS           482
#define IDM_BOM_UTF7_A                  515
#define IDM_BOM_UTF7_B                  516
#define IDM_BOM_UTF7_C                  517
#define IDM_BOM_UTF7_D                  518
#define IDM_BOM_UTF7_E                  519
#define IDM_BOM_UTF8                    521
#define IDM_BOM_UTF16                   522
#define IDM_BOM_UTF16_BE                523
#define IDM_BOM_UTF32                   524
#define IDM_BOM_UTF32_BE                525
#define IDM_ADD_TAG                     530
#define IDM_REMOVE                      531
#define IDM_REMOVE_ALL                  532
#define IDM_CLEAN_ALL                   533
#define IDM_ANNOTATE                    534
#define IDM_DRAW_LINE                   535
#define IDM_DRAW_IMAGE                  536
#define IDM_DRAW_RECTANGLE              537
#define IDM_DRAW_CIRCLE                 538
#define IDM_FADEOUT_ANNOTATIONS         540
#define IDM_COLOR_TAG0                  550
#define IDM_LINE_THICK1                 601
#define IDM_LINE_THICK2                 602
#define IDM_LINE_THICK4                 604
#define IDM_LINE_STRAIGHT               610
#define IDM_LINE_ARROW                  611
#define IDM_LINE_ARROW2                 612
#define IDM_LINE_WAVY                   613
#define IDM_COLOR_OUT0                  700
#define IDM_COLOR_IN_TRANSPARENT        750
#define IDM_COLOR_IN0                   751
#define IDM_GOTO_REGION0                800
#define IDC_RADIO_DATABYTES             801
#define IDC_RADIO_DATALINES             802
#define IDC_EDIT_RANGESTART             804
#define IDC_EDIT_RANGEBYTES             805
#define IDC_EDIT_RANGELINES             806
#define IDC_PRINT_PAGE_VIEW             807
#define IDC_RADIO_COPY                  808
#define IDC_RADIO_SAVE                  809
#define IDC_STATIC_PREVIEW              810
#define IDC_CHECK_SEGREGATE_ANNOTS      811
#define IDC_EDIT_LINENUM1               812
#define IDC_EDIT_LINENUM2               813
#define IDC_EDIT_PAGE_LINENUM1          814
#define IDC_EDIT_PAGE_LINENUM2          815
#define IDC_EDIT_PAGE1                  816
#define IDC_EDIT_PAGE2                  817
#define IDC_CHECK_GROUPNOTES            819
#define IDC_CHECK_FITTOPAGEWIDTH        820
#define IDC_STATIC_PAGE1                821
#define IDC_STATIC_PAGE2                822
#define IDC_STATIC_PAGENUM1             823
#define IDC_STATIC_PAGENUM2             824
#define IDC_SPIN_TOP                    825
#define IDC_SPIN_LEFT                   826
#define IDC_SPIN_RIGHT                  827
#define IDC_SPIN_BOTTOM                 828
#define IDC_EDIT_MARGIN_TOP             830
#define IDC_EDIT_MARGIN_LEFT            831
#define IDC_EDIT_MARGIN_RIGHT           832
#define IDC_EDIT_MARGIN_BOTTOM          833
#define IDC_EDIT_FONTNAME               837
#define IDC_EDIT_FONTSIZE               838
#define IDC_SPIN_FONTSIZE               839
#define IDC_COMBO_OUTLINE_COLOR         851
#define IDC_COMBO_INTERIOR_COLOR        852
#define IDC_EDIT_OFFSET                 853
#define IDC_EDIT_LENGTH                 854
#define IDC_EDIT_NOTE                   855
#define IDC_COLOR_SAMPLE                856
#define IDC_CHECK_GRAYTEXT              857
#define IDC_HEXDUMPWND                  900
#define IDC_HSCROLLBAR                  901
#define IDC_VSCROLLBAR                  902
#define IDC_SEARCHSTRING                903
#define IDC_RADIO_UTF8                  910
#define IDC_RADIO_UTF16                 911
#define IDC_RADIO_HEX                   912
#define IDC_HEXIMAGE_FRAME              920
#define IDC_RADIO_FORWARD               930
#define IDC_RADIO_BACKWARD              931
#define IDC_ANNOTATION_EDITCTRL0        950

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1230
#define _APS_NEXT_COMMAND_VALUE         2542
#define _APS_NEXT_CONTROL_VALUE         2840
#define _APS_NEXT_SYMED_VALUE           10000
#endif
#endif
